ConstructionAlerts/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using ConstructionAlerts.Areas.HelpPage.Models;

namespace ConstructionAlerts.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View("Error");
        }
    }
}

ConstructionAlerts/Controllers/AlertController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ConstructionAlerts.Models;

namespace ConstructionAlerts.Controllers
{
    public class AlertController : Controller
    {
        //
        // GET: /Alert/
        public ActionResult Index()
        {
            List<Alert> alerts = new List<Alert>();

            Alert test = new Alert();
            test.AlertName = "My WorK Route";
            test.range = "5 miles";

            Alert test2 = new Alert();
            test2.AlertName = "My route to school";
            test2.range = "5 miles";
            alerts.Add(test2);

            Alert test3 = new Alert();
            test3.AlertName = "Around my house";
            test3.range = "5 miles";
            alerts.Add(test3);

            Alert test4 = new Alert();
            test4.AlertName = "Around the Ice Hogs";
            test4.range = "5 miles";
            alerts.Add(test4);

            alerts.Add(test);
            return View(alerts);
        }

        //
        // GET: /Alert/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Alert/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Alert/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Alert/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Alert/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Alert/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Alert/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ConstructionAlerts/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @RenderSection("header", required: false)

</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Barrel Dodger", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
@if (Request.IsAuthenticated)
{
    <li>@Html.ActionLink("My Alerts", "Index", "Alert", new { area = "" }, null)</li>
}

                    <li>@Html.ActionLink("Add Closure", "AddClosure", "Home", new { area = "" }, null)</li>
                    @*<li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>*@
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Barrel Dodger</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>